#!/bin/bash
IMS_PATH=/home/gustavo/devel/personal/python/ims-py
echo "IMS started"
config_file=$1
config_data=$(cat $config_file | tr -s '\n\t ' ' ')

echo "Loading configuration file $1"

redis-cli hset ims config "$config_data"
redis-cli hset ims base_path "$IMS_PATH"

echo "Starting scene_config_viewer process"
python3 $IMS_PATH/gui/scene_config_viewer.py &
redis-cli lpush ims_pids $!