#!/bin/bash

RUNNING=$(redis-cli llen ims_pids)

if [ "$RUNNING" -ne "0" ]
then
	echo "IMS instance already running"
	exit 1
fi

IMS_PATH=/home/gustavo/devel/personal/python/ims-py
echo "IMS started"
config_file=$1
config_data=$(cat $config_file | tr -s '\n\t ' ' ')

redis-cli flushdb

echo "Loading configuration file $1"

redis-cli hset ims config_file "$IMS_PATH/$1"
redis-cli hset ims config "$config_data"
redis-cli hset ims base_path "$IMS_PATH"

echo "Starting ims_main process"
python3 $IMS_PATH/nodes/ims_main.py &
redis-cli lpush ims_pids $!

echo "Starting legs_state_plotter process"
python3 $IMS_PATH/utils/legs_state_plotter.py &
redis-cli lpush ims_pids $!

sleep 2

# start range publishers
rs_name_list=$(redis-cli get ims.rs_name_list)

for i in $rs_name_list
do
	rs_src=$(redis-cli get ims.rs.$i.src)
	
	echo "Starting publisher for range sensor $i: $rs_src"	
	python3 $IMS_PATH/nodes/laser_publisher.py $i $rs_src &
	redis-cli lpush ims_pids $!
	
	sleep 0.5
	
	echo "Starting bg_remove for range sensor $i: $rs_src"	
	python3 $IMS_PATH/nodes/laser_bg_remove.py $i &
	redis-cli lpush ims_pids $!
	
	sleep 0.5
	
	echo "Starting pol2cart for range sensor $i: $rs_src"	
	python3 $IMS_PATH/nodes/laser_pol2cart.py $i "no_bg" &
	redis-cli lpush ims_pids $!
	
done

echo $rs_name_list[1]

#-----